{
	"version": 1533225395,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/dog-sheet0.png",
		"images/dog-sheet1.png",
		"images/chao-sheet0.png",
		"images/boy-sheet0.png",
		"images/spritedomenu-sheet0.png",
		"images/home-sheet0.png",
		"images/zumbi-sheet0.png",
		"images/sensor1-sheet0.png",
		"images/pa-sheet0.png",
		"images/portao-sheet0.png",
		"images/alavanca-sheet0.png",
		"images/alavanca-sheet1.png",
		"images/itemdecura-sheet0.png",
		"images/caixa-sheet0.png",
		"images/placa1-sheet0.png",
		"images/logo-sheet0.png",
		"images/logo-sheet1.png",
		"images/logo-sheet2.png",
		"images/logo-sheet3.png",
		"images/lixotoxico-sheet0.png",
		"images/elevador-sheet0.png",
		"images/bomba-sheet0.png",
		"images/bomba-sheet1.png",
		"images/bomba-sheet2.png",
		"images/belevador-sheet0.png",
		"images/bolsa-sheet0.png",
		"images/placaperigo-sheet0.png",
		"images/espinhos-sheet0.png",
		"images/espinhos-sheet1.png",
		"images/espinhos-sheet2.png",
		"images/minas-sheet0.png",
		"images/minas-sheet1.png",
		"images/minas-sheet2.png",
		"images/barradevida-sheet0.png",
		"images/barradevida-sheet1.png",
		"images/barradevida-sheet2.png",
		"images/spritefont.png",
		"images/sensorataque-sheet0.png",
		"images/fade-sheet0.png",
		"images/nbomba-sheet0.png",
		"images/bmusica-sheet0.png",
		"images/bmusica-sheet1.png",
		"images/bsom-sheet0.png",
		"images/bsom-sheet1.png",
		"images/sbomba-sheet0.png",
		"images/fase2-sheet0.png",
		"images/fase1-sheet0.png",
		"images/bgfase3-sheet0.png",
		"images/scasa-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/cachorro morrendo.m4a",
		"media/cachorro morrendo.ogg",
		"media/curando.m4a",
		"media/curando.ogg",
		"media/efeito sonoro-estrelas.m4a",
		"media/efeito sonoro-estrelas.ogg",
		"media/latido do dog.m4a",
		"media/latido do dog.ogg",
		"media/rosnado forte.m4a",
		"media/rosnado forte.ogg",
		"media/rosnado fraco.m4a",
		"media/rosnado fraco.ogg",
		"media/tap tap.m4a",
		"media/tap tap.ogg",
		"media/zombie morrendo.m4a",
		"media/zombie morrendo.ogg",
		"media/fase runner.m4a",
		"media/fase runner.ogg",
		"media/musica jogando.m4a",
		"media/musica jogando.ogg",
		"media/musica da splash-[audiotrimmer.com].m4a",
		"media/musica da splash-[audiotrimmer.com].ogg",
		"media/música- game over.m4a",
		"media/música- game over.ogg",
		"media/musicamenu.ogg",
		"media/rise of spirit.ogg",
		"media/rumble.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}